import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';
import { mkdir } from 'node:fs/promises';

const fixture = resolve('../dev/plans/evidence/p01/source-a.mp4');
test('local editor completes editing, playback, export and clear without upload', async ({ page }, info) => {
  const errors: string[] = [], outbound: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (!request.url().startsWith(process.env.VIEWKIT_TEST_URL || 'http://127.0.0.1:5173') && !request.url().startsWith('blob:') && !request.url().startsWith('data:')) outbound.push(request.url()); });
  await page.goto('/');
  await expect(page.locator('[data-lane]')).toHaveCount(10);
  await page.getByTestId('media-input').setInputFiles({ name: 'bad.txt', mimeType: 'text/plain', buffer: Buffer.from('not media') });
  await expect(page.getByRole('status').first()).toContainText('unsupported');
  await expect(page.locator('[data-source-id]')).toHaveCount(0);
  await page.getByTestId('media-input').setInputFiles(fixture);
  await expect(page.locator('[data-source-id]')).toHaveCount(1);
  await page.getByTitle('add to timeline at playhead').click();
  await expect(page.locator('[data-clip-id]')).toHaveCount(1);
  await page.getByTitle('add to timeline at playhead').click();
  await expect(page.locator('[data-clip-id]')).toHaveCount(2);
  const first = page.locator('[data-clip-id]').first();
  let bounds = (await first.boundingBox())!;
  await page.mouse.click(bounds.x + 60, bounds.y + 12);
  await page.getByLabel('rotation', { exact: true }).fill('90');
  await page.getByLabel('rotation', { exact: true }).press('Enter');
  await page.getByLabel('scale x', { exact: true }).fill('0.5');
  await page.getByLabel('scale x', { exact: true }).press('Enter');
  await page.getByLabel('volume value', { exact: true }).fill('50');
  await page.getByLabel('volume value', { exact: true }).press('Enter');
  await expect(page.getByLabel('volume value', { exact: true })).toHaveValue('50');
  await page.getByLabel('stage width', { exact: true }).fill('0');
  await page.getByRole('button', { name: 'apply stage size' }).click();
  await expect(page.locator('.stage-heading')).toContainText('1280 × 720');
  await page.getByLabel('stage width', { exact: true }).fill('1280');
  await page.getByRole('button', { name: 'apply stage size' }).click();
  // Drag the right edge; this must shorten the source rather than move the entire clip.
  bounds = (await first.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width - 3, bounds.y + 15);
  await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width - 70, bounds.y + 15, { steps: 8 }); await page.mouse.up();
  const trimmed = (await first.boundingBox())!;
  expect(trimmed.width).toBeLessThan(bounds.width - 50);
  await page.keyboard.press('Control+z');
  expect((await first.boundingBox())!.width).toBeCloseTo(bounds.width, 0);
  await page.keyboard.press('Control+y');
  // Copy and paste the selected clip, preserving occupied-position overlap.
  await page.keyboard.press('Control+c'); await page.keyboard.press('Control+v');
  await expect(page.locator('[data-clip-id]')).toHaveCount(3);
  await page.keyboard.press('Control+z');
  await expect(page.locator('[data-clip-id]')).toHaveCount(2);
  await page.getByRole('button', { name: 'play', exact: true }).click();
  await page.waitForTimeout(1400);
  await page.getByRole('button', { name: 'pause', exact: true }).click();
  expect(await page.locator('.timecode').textContent()).not.toBe('00:00:00:00');
  await page.getByTitle('next frame', { exact: true }).click();
  bounds = (await first.boundingBox())!;
  await page.mouse.click(bounds.x + 40, bounds.y + 12);
  await page.getByTitle('split at playhead (S)').click();
  await expect(page.locator('[data-clip-id]')).toHaveCount(3);
  const evidence = resolve('../dev/plans/evidence/p06'); await mkdir(evidence, { recursive: true });
  await page.screenshot({ path: resolve(evidence, info.project.name + '-editor.png'), fullPage: true });
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'export mp4' }).click();
  const download = await downloadPromise;
  await download.saveAs(resolve(evidence, info.project.name + '-export.mp4'));
  await expect(page.getByRole('status').first()).toContainText('mp4 exported');
  await page.getByRole('button', { name: 'clear project', exact: true }).click();
  await page.getByRole('button', { name: 'keep editing' }).click();
  await expect(page.locator('[data-clip-id]')).toHaveCount(3);
  await page.getByRole('button', { name: 'clear project', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'clear project', exact: true }).click();
  await expect(page.locator('[data-clip-id]')).toHaveCount(0); await expect(page.locator('[data-source-id]')).toHaveCount(0);
  await page.keyboard.press('Control+z'); await expect(page.locator('[data-clip-id]')).toHaveCount(0);
  expect(errors).toEqual([]); expect(outbound).toEqual([]);
});
